version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
  - dependency-name: ts-node
    versions:
    - 9.1.1
